name: Publish Package to GitHub Packages

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@egeuysall'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build  # Replace with your build command if different
      
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
